config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :participants
  resources :courses
  resources :customers
  resources :comments, only: [:create, :destroy]

  root 'customers#index'

end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id          :integer          not null, primary key
#  family_name :string           not null
#  given_name  :string           not null
#  email       :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  company_id  :integer
#  post_id     :integer
#

class Customer < ActiveRecord::Base
    belongs_to :company
    belongs_to :post
    has_many :comments # 追加

    validates :family_name,
      presence: true,
      length: { maximum: 20 }
    validates :given_name,
      presence: true,
      length: { maximum: 20 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email,
      presence: true, format: { with: VALID_EMAIL_REGEX }
    validates :company_id,
      presence: true
    validates :post_id,
      presence: true

    def full_name
        full_name = family_name + given_name
        return full_name
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :show]

  def index
    # ページャ機能のgem kaminariのみ
    # @customers = Customer.page(params[:page])
    # 検索機能のgem ransack+kaminari
    @q = Customer.ransack(params[:q])
    @customers = @q.result.page(params[:page])
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        # format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        # format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html {
          redirect_to @customer,
          notice: 'Customer was successfully updated.'
        }
        # format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        # format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @comment = Comment.new
  end

  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(
      :family_name,
      :given_name,
      :email,
      :company_id,
      :post_id
    )
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
   <div class="alert alert-danger">
     <p><b><%= @customer.errors.count %>件のエラーがあります</b></p>

     <ul>
     <% @customer.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
  <% end %>
  <div class="form-group">
      <%= f.label :family_name, '性' %>
      <%= f.text_field :family_name, class: "form-control" %>
  </div>
  <div class="form-group">
      <%= f.label :given_name, '名' %>
      <%= f.text_field :given_name, class: "form-control" %>
  </div>
  <div class="form-group">
      <%= f.label :email, 'メールアドレス' %>
      <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
      <%= f.label :company_id, '所属する会社' %>
      <%= f.collection_select :company_id, Company.all, :id, :name, {}, { class: 'input-sm' } %>
  </div>
  <div class="form-group">
      <%= f.label :post_id, '役職' %>
      <%= f.collection_select :post_id, Post.all, :id, :name, {}, { class: 'input-sm' } %>
  </div>
  <% if @customer.new_record? %>
    <input type="submit" name="commit" value="登録" class="btn btn-primary">
  <% else %>
    <input type="submit" name="commit" value="編集" class="btn btn-warning">
  <% end  %>
<% end %>

app/views/customers/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>編集</h1>
    <%= render 'form' %>
    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#delete-customer">顧客情報を削除する</button>
  </div>
</div>


<!-- 下記のモーダルは通常は隠れているので、どこに書いてもＯＫ -->
<div class="modal fade" id="delete-customer">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">顧客情報の削除</h4>
      </div>
      <div class="modal-body">
        <p><%= @customer.family_name %>さんを削除しますか？</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
        <%= link_to '削除する', @customer, method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/customers/index.html.erb
<div class="row">
  <div class="col-lg-12">

    <%= search_form_for @q do |f| %>
      <div class="row">
        <div class="col-sm-2 col-xs-12">
          <div class="form-group">
            <%= f.label :family_name, "姓" %>
            <%= f.search_field :family_name_cont, class: "form-control input-sm"  %>
          </div> <!-- form-group -->
        </div> <!-- col-sm-2 col-xs-12 -->
        <div class="col-sm-2 col-xs-12">
          <div class="form-group">
            <%= f.label :given_name, "名" %>
            <%= f.search_field :given_name_cont, class: "form-control input-sm"  %>
          </div> <!-- form-group -->
        </div> <!-- col-sm-2 col-xs-12 -->
        <div class="col-sm-2 col-xs-12">
          <div class="form-group">
            <%= f.label :email, "メールアドレス" %>
            <%= f.search_field :email_cont, class: "form-control input-sm"  %>
          </div> <!-- form-group -->
        </div> <!-- col-sm-2 col-xs-12 -->
        <div class="col-sm-2 col-xs-12">
          <div class="form-group">
            <%= f.label :company_name, "会社名" %>
            <%= f.search_field :company_name_cont, class: "form-control input-sm"  %>
          </div> <!-- form-group -->
        </div> <!-- col-sm-2 col-xs-12 -->
        <div class="col-sm-2 col-xs-12">
          <div class="form-group">
            <%= f.label :post_name, "役職名" %>
            <%= f.search_field :post_name_cont, class: "form-control input-sm"  %>
          </div> <!-- form-group -->
        </div> <!-- col-sm-2 col-xs-12 -->
      </div> <!-- row -->
      <div class="row">
        <div class="col-xs-12 text-center">
          <%= f.submit "検索", class: "btn btn-default" %>
        </div>
      </div>
    <% end %>
    <h1>顧客情報一覧</h1>
    <p>お客様情報が表示されます。</p>
    <table class="table table-striped">
      <thead>
        <th><%= sort_link(@q, :family_name, "姓") %></th>
        <th><%= sort_link(@q, :given_name, "名") %></th>
        <th><%= sort_link(@q, :email, "メールアドレス") %></th>
        <th><%= sort_link(@q, :company_name, "会社") %></th>
        <th><%= sort_link(@q, :post_name, "役職") %></th>
        <th>コメント数</th>
        <th>リンク</th>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.family_name %></td>
            <td><%= customer.given_name %></td>
            <td><%= customer.email %></td>
            <td><%= customer.company.name %></td>
            <td><%= customer.post.name %></td>
            <td><%= customer.comments.count %></td>
            <td><%= link_to '詳細', customer, class: "btn btn-default btn-xs" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @customers %>
  </div> <!-- col-lg-12 -->
</div> <!-- row -->

<div class="row">
  <div class="col-lg-12">
    <div class="pull-left">
      <%= link_to '顧客新規追加', new_customer_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/customers/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>新規登録</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/customers/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>顧客詳細</h1>
    <dl>
      <dt>お名前</dt>
      <dd><%= @customer.full_name %></dd>
      <dt>電子メール</dt>
      <dd><%= @customer.email %></dd>
      <dt>会社</dt>
      <dd><%= @customer.company.name %></dd>
      <dt>役職</dt>
      <dd><%= @customer.post.name %></dd>
    </dl>
  </div>
</div>

<%= link_to '一覧', customers_path, { :class => 'btn btn-default' } %>
<%= link_to '編集', edit_customer_path, { :class => 'btn btn-warning' } %>

<hr>
<div class="row">
  <div class="col-lg-12">
    <h2>対応履歴</h2>
    <% @customer.comments.each do |comment| %>
      <div class="media">
        <div class="media-left">
          <% if comment.user.image_url.nil? %>
            <%= image_tag("http://placehold.jp/64x64.png", class: "media-object") %>
          <% else %>
            <%= image_tag(comment.user.image_url, class: "media-object", size: "64x64") %>
          <% end %>
        </div>
        <div class="media-body">
          <%= simple_format(comment.body) %>
          <p class="text-muted">
            by <%= comment.user.family_name %>
          </p>
          <p class="text-muted">
            投稿日時：<%= comment.created_at.strftime('%Y/%m/%d %H:%M') %>
            <%= link_to "削除する", comment_path(comment), method: :delete %>
          </p>
        </div>
      </div>
    <% end %>
  </div> <!-- col-lg-12 ->
</div> <!- row -->

<div class="row">
  <div class="col-lg-12">
    <%# 放っておくと,自分がいるviewのcontrollerに投げるので,投げ先を変更してやる %>
    <%= form_for @comment, url: { controller: :comments, action: :create } do |f| %>
      <div class="form-group">
        <%= f.label :body, "対応内容" %>
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <%= f.hidden_field :customer_id, value: @customer.id %>
      <%= f.submit "送信", class: "btn btn-primary" %>
    <% end %>
  </div> <!-- col-lg-12 ->
</div> <!- row -->